name: CI
on:
  pull_request:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Env
        run: nix develop
      - name: Run Checks
        run: dev check
  deploy:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/main'
    needs: test
    steps:
      - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Env
        run: nix develop
      - name: Compile
        run: dev package
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
