name: CI
on:
  pull_request:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 16
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.${{ matrix.java }}"
    - name: Build and test
      run: sbt -v -Dfile.encoding=UTF8 +test
      shell: bash
  deploy:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 16
    runs-on: ${{ matrix.os }}
    if: success() && github.ref == 'refs/heads/main'
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.${{ matrix.java }}"
      - name: ScalaVersion
        run: echo "scala_version=${{sbt about | grep 'The current project is built against Scala' | sed  's/[^0-9.]//g'}}" >> $GITHUB_ENV
      - name: Compile
        run: sbt fullLinkJS
      - name: Package
        run: |
          mkdir dist
          cp js/target/${{env.scala_version}}/gol-opt/* ./dist/
          cp index.html dist/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dist
